version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 80:80
      - 3000:3000
    env_file:
      - .env
    networks:
      - express-api-net
    volumes:
      - '.:/app'
    depends_on:
      - mysql
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql
    ports:
        - '3306:3306'
    env_file: .env
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
        - 'express-api-mysql:/var/lib/mysql'
    networks:
        - express-api-net
    healthcheck:
        test:
            - CMD
            - mysqladmin
            - ping
            - '-p${DB_PASSWORD}'
        retries: 3
        timeout: 5s
networks:
    express-api-net:
        driver: bridge
volumes:
    express-api-mysql:
        driver: local